---
driver:
  name: vagrant
  vm_hostname: rwebsrv1
  customize:
    memory: <%= ENV['WEB_RAM'] %>
    cpus: <%= ENV['WEB_CPU'] %>
    name: rwebsrv1

  network:
   - ['private_network', ip: '10.1.1.31']

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['chef_release'] %>
  install_strategy: always
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: myrhel7
    provisioner:
      download_url: http://10.1.1.30/media/chef-<%= ENV['chef_release'] %>-1.el7.x86_64.rpm

suites:
  - name: rwebsrv1
    run_list:
      - recipe[rwebsrv::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
