---
driver:
  name: vagrant
  vm_hostname: rwebsrv1
  customize:
    memory: <%= ENV['WEB_RAM'] %>
    cpus: <%= ENV['WEB_CPU'] %>
    name: rwebsrv1

  network:
   - ['private_network', ip: '10.1.1.31']

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: myrhel-7.6

suites:
  - name: rwebsrv1
    run_list:
      - recipe[rwebsrv::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
